### ISSUE TITLE
Please consider updating autotool scripts

### ISSUE THREAD

**Issue by TinySnow** [utelle/wxsqlite3#105]
Hello, I'm from ArchRISC-V Team, a community porting Arch Linux software to RISC-V architecture.

### Description

While packaging `wxsqlite3`, we found an error.

### Error information

```bash
checking build system type... ./config.guess: unable to guess system type
This script, last modified 2009-11-20, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD
If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2009-11-20

uname -m = riscv64
uname -r = 5.18.7-arch1-1
uname -s = Linux
uname -v = #1 SMP PREEMPT_DYNAMIC Sat, 25 Jun 2022 20:22:01 +0000

/usr/bin/uname -p = unknown
/bin/uname -X     =

hostinfo               =
/bin/universe          =
/usr/bin/arch -k       =
/bin/arch              =
/usr/bin/oslevel       =
/usr/convex/getsysinfo =

UNAME_MACHINE = riscv64
UNAME_RELEASE = 5.18.7-arch1-1
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP PREEMPT_DYNAMIC Sat, 25 Jun 2022 20:22:01 +0000
configure: error: cannot guess build type; you must specify one
```

### Solved

Added `autoreconf` in the `prepare()` function in the `PKGBUILD`. It can solve this problem.
Here is the code:

```bash
autoupdate
autoreconf -fiv
```

### Advice

Please consider updating the configure script tools **(Especially the `config.guess` file)**.
We solved it through patch we created, however, as part of our duty, we do suggest our upstreams doing this once and for all instead.

Sincerely thanks.
:)

ArchRISC-V Team,
TinySnow

**Comment by utelle** [comment]
> While packaging `wxsqlite3`, we found an error.
> 
> ```shell
> checking build system type... ./config.guess: unable to guess system type
> This script, last modified 2009-11-20, has failed to recognize
> the operating system you are using. It is advised that you
> download the most up to date version of the config scripts from
>   http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
> and
>   http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD
> ```

In commit 982542a72776fad856966549439eba9efb095582 I updated the files `config.guess` and `config.sub` to the latest versions (downloaded from the links given above).

> ```shell
> config.guess timestamp = 2009-11-20
> ```

However, I'm a bit confused, because the timestamp in the previous version of `config.guess` used in my project was `timestamp='2014-03-23'` (and **not** `2009-11-20` and AFAICT a version with that timestamp was never used by me). Are you sure that the correct repository is referenced when packaging this component?

**Comment by TinySnow** [comment]
@utelle Sorry, it seems that I have used the similar error message, which happened on another package.
However, `wxsqlite3` truly can't be packaged because of `config.guess`. And I retried it, this is the correct error info, that have the same timestamp.
Here is the info, (to show this info belongs to `wxsqlite3`, I bold something):

```
  **-> Extracting wxsqlite3-4.7.8.tar.gz with bsdtar**
==> Starting build()...
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether make supports nested variables... (cached) yes
checking build system type... ./admin/build-aux/config.guess: unable to guess system type

**This script, last modified 2014-03-23, has failed to recognize**
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

If the version you run (./admin/build-aux/config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

**config.guess timestamp = 2014-03-23**

uname -m = riscv64
uname -r = 5.18.7-arch1-1
uname -s = Linux
uname -v = #1 SMP PREEMPT_DYNAMIC Sat, 25 Jun 2022 20:22:01 +0000

/usr/bin/uname -p = unknown
/bin/uname -X     =

hostinfo               =
/bin/universe          =
/usr/bin/arch -k       =
/bin/arch              =
/usr/bin/oslevel       =
/usr/convex/getsysinfo =

UNAME_MACHINE = riscv64
UNAME_RELEASE = 5.18.7-arch1-1
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP PREEMPT_DYNAMIC Sat, 25 Jun 2022 20:22:01 +0000
configure: error: cannot guess build type; you must specify one
==> ERROR: A failure occurred in build().
```

I apologized for my carelessness, and hope that we can get it fixed as soon as possible.
Thanks.

**Comment by utelle** [comment]
Release [wxSQLite3 4.8.2](https://github.com/utelle/wxsqlite3/releases/tag/v4.8.2), made a couple of hours ago, uses the updated `config.guess` and `config.sub` files. Please give it a try using the distribution file [wxsqlite3-4.8.2.tar.gz](https://github.com/utelle/wxsqlite3/archive/refs/tags/v4.8.2.tar.gz). Let me know if further adjustments are necessary.

**Comment by TinySnow** [comment]
@utelle ok, thanks, I flagged arch linux community to tell that this package is out-of-date.
I'll retry it with new release after arch update this package, and I'll notify you a new comment to tell it succeed or not and whether we should do other fixes or not.
Thanks.

**Comment by utelle** [comment]
If I see it correctly the _ArchLinux_ package [wxsqlite3](https://archlinux.org/packages/community/x86_64/wxsqlite3/) was updated today. So, I guess you should be able to retry packaging for Risc-V.

**Comment by TinySnow** [comment]
@utelle I retried it, and it succeed.
Thanks for your cooperation and support.
We can close the issue now.
