### ISSUE TITLE
cipherName is corrupted in wxSQLite3Cipher::SetCipher()

### ISSUE THREAD

**Issue by yzhgu** [utelle/wxsqlite3#109]
win10 + vs2019 + wxWidgets 3.2.21;
I run into a problem that wxSQLite3Cipher::SetCipher() is always return false. When I debug into this function, I found the const char* cipherName is corrupted. But if I first duplicate the wxString returned by GetCipherName(cipherType), then the result is fine. Did I do something wrong? My project character set is unicode.

**corrupted cipherName:**
![corrupted](https://user-images.githubusercontent.com/7881691/222064231-87f21543-e254-4b29-af0f-f1629cb4aa7c.png)
**right cipherName:**
![fine](https://user-images.githubusercontent.com/7881691/222064261-2c530528-305c-493f-a443-eb92a9c94376.png)

**Comment by utelle** [comment]
> win10 + vs2019 + wxWidgets 3.2.21; I run into a problem that `wxSQLite3Cipher::SetCipher()` is always return false. When I debug into this function, I found the const char* cipherName is corrupted. But if I first duplicate the wxString returned by GetCipherName(cipherType), then the result is fine. Did I do something wrong? My project character set is unicode.

Thanks for reporting this problem. Most likely the temporary object returned by method `wxSQLite3Cipher::GetCipherName()` or `wxString::utf8_str()` is destroyed, before it can be accessed by the following code. And therefore the local variable `cipherName` points to some invalid data. As you already detected the fix will be to save the result of `wxSQLite3Cipher::GetCipherName()` in a local variable. I will adjust the code accordingly.

**Comment by yzhgu** [comment]
Many thanks for your support!
