### ISSUE TITLE
Build error when using CMake on Linux

### ISSUE THREAD

**Issue by lszl84** [utelle/wxsqlite3#119]
Ubuntu 22.04
gcc 13.2.0
latest master  (c231fdb4b053b9701f0a04de7a57dea1f94f05bb)

When building the project using cmake:

```
cmake -S build -B b_out
cmake --build b_out
```

I'm getting numerous errors, e.g.

```
/home/parallels/wxsqlite3/src/sqlite3mc_amalgamation.c: In function ‘mcCheckValidName’:
/home/parallels/wxsqlite3/src/sqlite3mc_amalgamation.c:311587:3: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
311587 |   CipherName* cipherNameTable = &globalCipherNameTable[0];
       |   ^~~~~~~~~~
```

See the attached log for details.
[build_log.txt](https://github.com/user-attachments/files/18270189/build_log.txt)

**Comment by utelle** [comment]
> Ubuntu 22.04
> gcc 13.2.0
> latest master ([c231fdb](https://github.com/utelle/wxsqlite3/commit/c231fdb4b053b9701f0a04de7a57dea1f94f05bb))

_wxSQLite3_ is known to be compilable and usable under _Ubuntu_ using a recent compiler like _gcc 13.2.0_. This is checked via a GitHub CI workflow.

> When building the project using cmake:

Currently, _wxSQLite3_ doesn't have official cmake support. And I don't know what exactly your _cmake_ commands produce.

> ```
> /home/parallels/wxsqlite3/src/sqlite3mc_amalgamation.c: In function ‘mcCheckValidName’:
> /home/parallels/wxsqlite3/src/sqlite3mc_amalgamation.c:311587:3: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
> 311587 |   CipherName* cipherNameTable = &globalCipherNameTable[0];
>        |   ^~~~~~~~~~
> ```

Obviously, the C source code is compiled according to the (very old) C90 standard. The autoconf build files coming with wxSQLite3 use the C99 standard (also quiet old, but new enough to support certain features used by the current SQLite source code).

> See the attached log for details. [build_log.txt](https://github.com/user-attachments/files/18270189/build_log.txt)

You don't expect me to dig through 200+ kB of warnings and error messages without knowing the actual compiler options used, do you?

AFAICT all **errors** are related to the above mentioned use of the **C90** standard. **Use the C99** standard and the error messages should go away.

**Comment by lszl84** [comment]
> > See the attached log for details. [build_log.txt](https://github.com/user-attachments/files/18270189/build_log.txt)
> 
> You don't expect me to dig through 200+ kB of warnings and error messages without knowing the actual compiler options used, do you?
> 
> AFAICT all **errors** are related to the above mentioned use of the **C90** standard. **Use the C99** standard and the error messages should go away.

Did not expect such passive-aggressive tone to be honest.

I don't expect you to go through 200+ kB of warnings and error messages. Also, I'm not providing the exact complier options used on purpose - because that's what the bug is all about: the CMake script is supposed to provide correct compiler flags and options, so that the standard CMake compilation works:

```
cmake -S source-folder-with-cmakelists-txt -B output-build-folder
cmake --build output-build-folder
```

Check out my repo (https://github.com/lszl84/my_wxsqlite.git), where I put together your source files along with a super simple CMakeLists.txt - the project builds without any problems with:

```
cmake -S . -B build_dir
cmake --build build
```

It looks to me that your CMakeLists.txt is overly complicated and does not seem to work on Linux. Are there plans to fix that script? Or remove it? Or add some information to the README, that the CMake support is experimental and may not work?

**Comment by utelle** [comment]
I have to admit that I completely forgot the `CMakeLists.txt` file in the build directory. That file was provided by a user of _wxSQLite3_ many years ago. I never used it myself.

> It looks to me that your CMakeLists.txt is overly complicated and does not seem to work on Linux.

That may well be the case. 

> Are there plans to fix that script? Or remove it? Or add some information to the README, that the CMake support is experimental and may not work?

Actually, there is the (still open) issue #60. In my last [comment](https://github.com/utelle/wxsqlite3/issues/60#issuecomment-751440591) to that issue the current state of CMake support is described. CMake is not mentioned in the README, because it is not officially supported.

Most likely the best approach would be to **_replace_** the existing `CMakeLists.txt` file by something really useable and portable. Additionally, it would be important to add a CMake test to the GitHub CI workflow, so that working CMake support can be verified automatically.

If someone with profound CMake knowledge provides such CMake build support, I will add/update the necessary files.

**Comment by utelle** [comment]
I added a note about the experimental state of CMake support to the README.

Currently I have no plans to work on CMake support myself, due to lack of experience with CMake.
