### ISSUE TITLE
Build failed 3.5.1 with wx 3.0.3 or wx 3.1

### ISSUE THREAD

**Issue by vitlav** [utelle/wxsqlite3#12]
src/wxsqlite3.cpp: At global scope:
src/wxsqlite3.cpp:4134:1: error: cannot convert 'const char*' to 'const wxChar* {aka const wchar_t*}' in initialization
 };
 ^
src/wxsqlite3.cpp:4134:1: error: cannot convert 'const char*' to 'const wxChar* {aka const wchar_t*}' in initialization
src/wxsqlite3.cpp:4134:1: error: cannot convert 'const char*' to 'const wxChar* {aka const wchar_t*}' in initialization
src/wxsqlite3.cpp:4134:1: error: cannot convert 'const char*' to 'const wxChar* {aka const wchar_t*}' in initialization
src/wxsqlite3.cpp:4134:1: error: cannot convert 'const char*' to 'const wxChar* {aka const wchar_t*}' in initialization
src/wxsqlite3.cpp:4134:1: error: cannot convert 'const char*' to 'const wxChar* {aka const wchar_t*}' in initialization
src/wxsqlite3.cpp:4134:1: error: cannot convert 'const char*' to 'const wxChar* {aka const wchar_t*}' in initialization
src/wxsqlite3.cpp:4134:1: error: cannot convert 'const char*' to 'const wxChar* {aka const wchar_t*}' in initialization
src/wxsqlite3.cpp:4134:1: error: cannot convert 'const char*' to 'const wxChar* {aka const wchar_t*}' in initialization
src/wxsqlite3.cpp:4134:1: error: cannot convert 'const char*' to 'const wxChar* {aka const wchar_t*}' in initialization
src/wxsqlite3.cpp:4134:1: error: cannot convert 'const char*' to 'const wxChar* {aka const wchar_t*}' in initialization
src/wxsqlite3.cpp:4134:1: error: cannot convert 'const char*' to 'const wxChar* {aka const wchar_t*}' in initialization
In file included from /usr/include/wx-3.1/wx/debug.h:19:0,
                 from /usr/include/wx-3.1/wx/defs.h:693,
                 from /usr/include/wx-3.1/wx/wxprec.h:12,
                 from src/wxsqlite3.cpp:18:
src/wxsqlite3.cpp: In static member function 'static wxString wxSQLite3Database::LimitTypeToString(wxSQLite3LimitType)':
src/wxsqlite3.cpp:4140:35: error: cannot convert 'const char*' to 'const wxChar* {aka const wchar_t*}' in initialization
   const wxChar* limitString = wxS("Unknown");
                                   ^
/usr/include/wx-3.1/wx/chartype.h:239:20: note: in definition of macro 'wxS'
     #define wxS(x) x

**Comment by utelle** [comment]
Interestingly the continuous integration on travis did not fail for wxWidgets 3.0.2.

Nevertheless I adjusted the code, so that it should now compile without problems. 

Please check it out.

**Comment by vitlav** [comment]
Thank you, it fixes build both with 3.0.3 and 3.1 for me.
