### ISSUE TITLE
Issues with building wxsqlite3-3.5.3 on gcc - setup.h

### ISSUE THREAD

**Issue by stemsin** [utelle/wxsqlite3#14]
Hi,

I'm not able to build the latest version.
wxWidgets-3.1.0
TDM-GCC  5.1.0

```
set COMMON_FLAGS=-f Makefile CODEC_TYPE=CODEC_TYPE_AES256 WXSQLITE3_HAVE_METADATA=1 SQLITE_HAS_CODEC=1 WXSQLITE3_HAVE_CODEC=1 SQLITE_CORE=1 THREADSAFE=1 SQLITE_SECURE_DELETE=1 SQLITE_SOUNDEX=1 SQLITE_ENABLE_COLUMN_METADATA=1 CXXFLAGS="-std=gnu++11 -fno-keep-inline-dllexport" WXWIN=%WXWIDGETS_ROOT_DIR%

mingw32-make.exe %COMMON_FLAGS% config=debug_x64 all
```
gives the following error:
```
"==== Building wxsqlite3 (debug_x64) ===="
wxsqlite3.cpp
In file included from c:/!ST/Tools.Develop/wxWidgets/include/wx/defs.h:20:0,
                 from c:/!ST/Tools.Develop/wxWidgets/include/wx/wxprec.h:12,
                 from ../src/wxsqlite3.cpp:18:
c:/!ST/Tools.Develop/wxWidgets/include/wx/platform.h:136:22: fatal error: wx/setup.h: No such file or directory
compilation terminated.
wxsqlite3.make:414: recipe for target 'obj/x64/Debug/wxsqlite3/wxsqlite3.o' failed
mingw32-make.exe[1]: *** [obj/x64/Debug/wxsqlite3/wxsqlite3.o] Error 1
Makefile:82: recipe for target 'wxsqlite3' failed
mingw32-make.exe: *** [wxsqlite3] Error 2
```
How do I fix this?

**Comment by utelle** [comment]
Unfortunately I don't have much experience in using the make toolchain. 

However, the file `wx/setup.h` is copied to the library/DLL directory of wxWidgets when wxWidgets itself is built. The path to this directory is set as follows in the wxSQLite3 makefiles: 

`$(wxRootDir)/lib/$(wxCompilerPrefix)$(wxArchSuffix)_lib/msw$(wxSuffix)`

All variables are defined in file `config.gcc`. I suspect that the variable `wxCompilerPrefix` (which has a default of `gcc510TDM`) might be different for your installation. If that is the case, you would have to either change file `config.gcc` or to specify the correct value on the command line.

**Comment by utelle** [comment]
IMHO your problem is not a genuine wxSQLite3 problem, but just a configuration problem in your environment. Since you did not respond, I assume your problem is solved. Therefore I close this issue.

**Comment by stemsin** [comment]
Yes, I managed to build it after some modifications in wxsqlite3.make file to match the naming convention of wxWidgets.
