### ISSUE TITLE
Buffer underflow issue

### ISSUE THREAD

**Issue by Adriatic1** [utelle/wxsqlite3#16]
PSV studio reports the following error on codec.c
codec.c	187	err	V568 It's odd that 'sizeof()' operator evaluates the size of a pointer to a class, but not the size of the 'ctx' class object.
codec.c	187	err	V512 A call of the 'memset' function will lead to underflow of the buffer 'ctx'.

In short, this line:
memset((char *) ctx, 0, sizeof(ctx)); /* In case it's sensitive */
should be replaced with:
memset((char *) ctx, 0, sizeof(MD5_CTX));       /* In case it's sensitive */

BR,
  Miroslav

**Comment by utelle** [comment]
Thanks for reporting the issue. I'll fix it for a future version.

**Comment by utelle** [comment]
The issue should now be fixed.
