### ISSUE TITLE
How to compile for Android use? 

### ISSUE THREAD

**Issue by lshAndroid** [utelle/wxsqlite3#18]
How to compile for Android use? Not through Cocos2dx framework to use, direct jni call method to make the encrypted database into a decrypted database? Ask for help, Thanks.

**Comment by utelle** [comment]
Unfortunately, I have no experience with developing for Android, so I can't give you much advice how to solve your issue.

However, the [SQLite Android documentation](https://www.sqlite.org/android/doc/trunk/www/index.wiki) might give you some hints. Especially, read the section about [SEE - SQlite Encryption Extension](https://www.sqlite.org/android/doc/trunk/www/see.wiki), since the encryption extension coming with `wxSQLite3` uses the same SQLite API as `SEE`. Instead of the source file `sqlite3.c` just reference the source file `sqlite3secure.c` in the build files. Depending on your needs you may have to add compiler defines to enable additional SQLite features.

Good luck!

**Comment by iamcxl369** [comment]
Hi @lshAndroid !

# 0x01. compiling sqlite3.c

```
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE:= libsqlite3

LOCAL_SRC_FILES:= sqlite3secure.c 

include $(BUILD_STATIC_LIBRARY)
```
# 0x02. compiling wxSqlite3 in Android.mk

```
google it
```

# 0x03. write your jni code use wxsqlite

the wxSqlite interface same with sqlite3.
```
void Java_com_iamcxl_wwww_wxsqlite3_MainActivity_cryptSqlite3Test(){
    LOGI("cryptSqlite3Test() >>>>>>\n");
    const char * sSQL;
    char * pErrMsg = 0;
    int ret = 0;
    sqlite3 * db = 0;

    ret = sqlite3_open("/storage/sdcard0/xxx.db", &db); // create a database
    
    ret = sqlite3_key_v2( db, "", "abcdefghijklmnopqrstuvwxyz", 26 ); //set the database password

    sSQL = "create table xxx(name varchar(20), student);";
    sqlite3_exec( db, sSQL, _callback_exec, 0, &pErrMsg ); //create the database

    sSQL = "insert into class values('name', 'iamcxl369');";
    sqlite3_exec( db, sSQL, _callback_exec_insert, 0, &pErrMsg ); // insert data to database

    sSQL = "select * from xxx;";
    sqlite3_exec( db, sSQL, _callback_exec_select, 0, &pErrMsg ); // query data from database

    ret =  sqlite3_rekey_v2( db, "", NULL, 0 ); // remove the password

    sqlite3_close_v2(db);  // close the db
    db = 0;
    LOGI("cryptSqlite3Test() <<<<<<\n");
}
```

**Comment by utelle** [comment]
Since @iamcxl369 described in detail, how to use the wxSQLite3 encryption extension in Android applications, I'm going to close this issue.

**Comment by malcolmjerry** [comment]
Download SQLite3MultipleCiphers, 
https://github.com/utelle/SQLite3MultipleCiphers

Put the arm64-v8a and armeabi-v7a  into /Assets/Plugins/Android   (For Unity3d)

Change the method name :
1. //[DllImport( "sqlite3", EntryPoint = "wxsqlite3_config" )]
    //internal static extern int wxsqlite3_config( IntPtr db, string param, int newValue );

  To this
      [DllImport( "sqlite3", EntryPoint = "sqlite3mc_config" )]
      internal static extern int sqlite3mc_config( IntPtr db, string param, int newValue );

2.  //[DllImport( "sqlite3", EntryPoint = "wxsqlite3_config_cipher" )]
     //internal static extern int wxsqlite3_config_cipher( IntPtr db, string cipherName, string paramName, int newValue );

  To this
   [DllImport( "sqlite3", EntryPoint = "sqlite3mc_config_cipher" )]
   internal static extern int sqlite3mc_config_cipher( IntPtr db, string cipherName, string paramName, int newValue );


Everything works now!

**Comment by utelle** [comment]
My project [SQLite3 Multiple Ciphers](https://github.com/utelle/SQLite3MultipleCiphers) started with version **1.3.7** to provide pre-compiled binaries for Android (see [latest release](https://github.com/utelle/SQLite3MultipleCiphers/releases/latest)). These binaries are built following the installation guide that can be found on the official [SQLite Android Bindings](https://www.sqlite.org/android) web page. Detailed instructions how to build the Android bindings on your own can be found [**here**](https://github.com/utelle/SQLite3MultipleCiphers/issues/91#issuecomment-1270117175).
