### ISSUE TITLE
Does this works with windows 8 store apps?

### ISSUE THREAD

**Issue by pallammadhukar** [utelle/wxsqlite3#22]
Hi Team,

We are using "wxSQLite.WinRT81" SDK,Version="3.8.7.2" as of now. We wanted to update the SQLite version.

But we coun't find the Visual Studio Extension. Can we use this "wxSQLite3" libs in my app.

I am confused with wxSQLite and "wxSQLite3". Is there any difference?

**Comment by utelle** [comment]
Unfortunately I'm not aware of such a component as `"wxSQLite.WinRT81" SDK,Version="3.8.7.2" `. Are you talking of [SQLite for Windows Runtime (Windows 8.1)](https://marketplace.visualstudio.com/items?itemName=SQLiteDevelopmentTeam.SQLiteforWindowsRuntimeWindows81)? If not, could you please provide a link from where you get the component you are talking of?

There exists an open source project [wxSQLite](https://sourceforge.net/projects/wxsqlite/). It provides a wxWidgets wrapper for **SQLite2**. However, it is heavily outdated and does **_not_** support **SQLite3**.

Then there is this project, [wxSQLite3](https://github.com/utelle/wxsqlite3). It supports **SQLite3** and includes a SQLite3 encryption extension (using AES 128 bit or AES 256 bit) that can also be used independently of the wxWidgets wrapper.

Finally, I know of [System.Data.SQLite](https://system.data.sqlite.org). It supports **SQLite3** and also includes a simple RC4 encryption extension. However, the encryption is weak and limited to Windows platforms.

**Comment by utelle** [comment]
Since you did not comment further, I'm going to close this issue.

IMHO it should be possible to use the SQLite3 encryption extension coming with wxSQLite3 together with any component based on SQLite3, since it uses the official SQLite3 API.
