### ISSUE TITLE
License of linking object files .o into another language (not using .dll)

### ISSUE THREAD

**Issue by lainz** [utelle/wxsqlite3#26]
Hi,
I have a commercial application using your library. I use this because it has encryption support.
Instead of using the .dll, I want to incorporate the .o files into my application (I'm using Free Pascal).

But I need to know if not using the .dll and just using the .o files is legal for a commercial application.

Thanks.

**Comment by utelle** [comment]
**wxSQLite3** is licensed under the [wxWidgets license](https://www.wxwidgets.org/about/licence/) (aka wxWindows license). This license corresponds to the [GNU Library General Public License v2 or later](https://spdx.org/licenses/LGPL-2.0-or-later.html) *plus* the [wxWindows exception](https://spdx.org/licenses/WxWindows-exception-3.1.html). Paragraph 2 of the exception reads

> The exception is that you may use, copy, link, modify and distribute under your own terms, binary object code versions of works based on the Library.

That is, you can use wxSQLite3 in binary form in your commercial application. At your discretion you can link statically or dynamically.

**Comment by lainz** [comment]
Thank You. Now the hard part, doing it really, but is nice that the License is so permissive.
Thanks for your time.
