### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Landslyde01** [utelle/wxsqlite3#33]
I downloaded SQLite3-master.zip.

1. Where do I extract the files to? EXACTLY where? I'm on Linux Mint.
2. Then what?

I'll be using wxSQLite3 with Code::Blocks.

**Comment by utelle** [comment]
The wxSQLite3 distribution (master or releases) just contain source code. That is, you should extract the files anywhere in your home directory which is appropriate for your software development.

How to compile wxSQLite3 on Linux is described in the `Installation` section of the `readme` file under the heading `wxGTK`. For Linux systems currently wxSQLite3 offers only the `autoconf`-based build system out of the box.

wxSQLite3 uses `premake5` to generate the build files. Unfortunately `premake5` does not yet support generating Code::Blocks project files.

**Comment by Landslyde01** [comment]
> The wxSQLite3 distribution (master or releases) just contain source code. That is, you should extract the files anywhere in your home directory which is appropriate for your software development.

This means I can just install them in say /home/wxsqlite3 folder? Or do the wxsqlite3 files have to be in a code::blocks folder?

**Comment by utelle** [comment]
You are welcome.
