### ISSUE TITLE
Is there any way to find out which cipher this database uses?

### ISSUE THREAD

**Issue by devbean** [utelle/wxsqlite3#34]
Is there any way to find out which cipher this database uses? `wxsqllite3_config(sqlite*, "cipher", -1)` could return the cipher ID after `open()` invoked. But there seems be no way to get this cipher ID using `SELECT`. I found out `SELECT wxsqlite3_config('cipher')` always return the global cipher name but not the one for instance. So what about adding this feature?

BTW, since we can change cipher at runtime, why there is a compile option called `CODEC_TYPE=CODEC_TYPE_AES256`?

**Comment by utelle** [comment]
> Is there any way to find out which cipher this database uses?

Well, it depends. The function `wxsqlite3_config` accesses a parameter table associated with the database connection. The table holds configuration parameters for each encryption type. In fact, there are 2 sets of configuration parameters: the default set and the transient set for the next encryption activation.

If you use `SELECT wxsqlite3_config('cipher');` you are accessing the transient set. That is, it will show the parameter values that will be used for the next encryption activation (`PRAGMA key=...`). That is, __before__ activating the encryption, `SELECT wxsqlite3_config('cipher');` will return the value from the transient set, but as soon as the next encryption activation took place, the parameters in the transient set are reverted to the values of the default set - and `SELECT wxsqlite3_config('cipher');` will return the default setting again. If you want to make your parameter settings persistent for the database connection, you will have to use for example `SELECT wxsqlite3_config('default:cipher', 'aes256cbc');`, that is, you have to use the `default:` prefix.

Usually your application should know which encryption scheme is in use. In case, a user of your application wants to open an encrypted database not created by your application, the user should know the encryption scheme that was used for that database, and your application should then ask the user for entering or selecting appropriate parameter settings.

However, you are asking for a method to detect which encryption scheme was used to encrypt a database. Such a method does not exist and never will. Looking at the raw data of an encrypted SQLite database file it is not even possible to tell for sure that it is a database file at all. To open such a database file successfully, you **have** to know the right parameter settings of the encryption scheme **and** the passphrase. (And if you were able to successfully open an encrypted database file, you already know the encryption parameters. That is, no need to query them from the database itself.)

> why there is a compile option called `CODEC_TYPE=CODEC_TYPE_AES256`?

With this compile time option you specify which encryption scheme will be used as the **default** encryption scheme - the encryption scheme used, if it is not explicitly selected by the application.

This option is important for legacy application that used a prior version of wxSQLite3 where the default encryption scheme was `aes128cbc` (or `aes256cbc` at the developer's discretion), while for wxSQLite3 version 4 and up the default encryption scheme is now `chacha20`.

**Comment by devbean** [comment]
Thank you. I think this answer is the very one I'm looking for. Maybe I should close this issue. Please reopen it if necessary.
