### ISSUE TITLE
CODEC_TYPE_* defines

### ISSUE THREAD

**Issue by emkey08** [utelle/wxsqlite3#37]
The [CODEC_TYPE defines](https://github.com/utelle/wxsqlite3/blob/master/sqlite3secure/src/codec.h#L37) can't be (easily) included by external code because `codec.h` isn't a self-sufficient header file.

Since the `CODEC_TYPE` defines are intended to be used for the `newValue` parameter of `wxsqlite3_config()`, it would be nice to have `sqlite3secure.h` define them as part of the interface.

**Comment by utelle** [comment]
I agree that it would be better to have these defines in `sqlite3secure.h`. I will change this soon.

**Comment by utelle** [comment]
Commit 6142b5c0687284c064c29f102a3a39d5d5d84a78 addresses this issue.
