### ISSUE TITLE
sample linking errors for mingw

### ISSUE THREAD

**Issue by ouch67** [utelle/wxsqlite3#41]
The treeview.make file has a couple issues that prevent it from building:

The library linking order is incorrect and it's missing the uxtheme lib.

I got release_x32 to build by changing the LIBS variable to be:

LIBS += ../lib/gcc_lib/libwxsqlite3$(wxFlavour).a -l$(wxBaseLibNamePrefix)_xml -l$(wxToolkitLibNamePrefix)adv -l$(wxToolkitLibNamePrefix)core -l$(wxBaseLibNamePrefix) -lwxjpeg$(wxSuffixDebug) -lwxpng$(wxSuffixDebug) -lwxzlib$(wxSuffixDebug) -lwxtiff$(wxSuffixDebug) -lwxexpat$(wxSuffixDebug) -lwxregex$(wxSuffix) -lcomctl32 -lrpcrt4 -lshell32 -lgdi32 -lkernel32 -luser32 -lcomdlg32 -lole32 -loleaut32 -ladvapi32 -loleacc -lwinspool -lwinmm -lshlwapi -luuid -lversion -lwsock32 -lwininet -luxtheme

minimal.make suffers from similar issues. Here is what worked for me to build release_x32:

LIBS += ../lib/gcc_lib/libwxsqlite3$(wxFlavour).a -l$(wxToolkitLibNamePrefix)core -l$(wxBaseLibNamePrefix) -lwxjpeg$(wxSuffixDebug) -lwxpng$(wxSuffixDebug) -lwxzlib$(wxSuffixDebug) -lwxtiff$(wxSuffixDebug) -lwxexpat$(wxSuffixDebug) -lwxregex$(wxSuffix) -lcomctl32 -lrpcrt4 -lshell32 -lgdi32 -lkernel32 -luser32 -lcomdlg32 -lole32 -loleaut32 -ladvapi32 -loleacc -lwinspool -lwinmm -lshlwapi -luuid -lversion -lwsock32 -lwininet -luxtheme

This was with mingw64 on win 7 with the following config:

i686-8.1.0-posix-sjlj-rt_v6-rev0

**Comment by utelle** [comment]
Thanks for reporting. I will check the issue.

**Comment by utelle** [comment]
Well, compiling with `mingw64` version `i686-7.2.0-posix-dwarf-rt_v5-rev1` worked for me right out of the box, without any issues. 

Yes, it is a different version of mingw than yours, but I find it strange that for your version the linking order doesn't work while it works for mine. 

Same for the additional runtime library `uxtheme`. I see that wxWidgets 3.1.1 introduced the additional dependency on uxtheme. However, I use the precompiled libraries for version 3.1.1, but do not experience any linker errors. Are you using static wxWidgets libraries or DLLs? For DLLs (as in the precompiled package) it seems to work without explicitly adding uxtheme for the linker.

**Comment by ouch67** [comment]
I am using the latest trunk of wxwidgets compiled statically without monolithic on.

Well if nothing else, at least you know what to change when everything catches up to release builds.

**Comment by utelle** [comment]
Obviously linking statically makes a difference. I will adjust the makefiles for the next release.

**Comment by utelle** [comment]
Although I understand that system library `uxtheme` has to be added to the list of link libraries, I really don't understand why you had to change the library linking order.

For the `treeview` sample you used the order `xml`, `adv`, `core`, `base` (I shortened the names to make the libraries easier to identify), while the order in the original makefile is `adv`, `core`, `xml`, `base`. The original order wouldn't work, if `xml` would depend on either `adv` or `core`, but this is not the case (see [wxWidgets library list](http://docs.wxwidgets.org/3.1/page_libs.html)).

That is, just adding `uxtheme` should have been enough to make it work for you.

**Comment by ouch67** [comment]
So I updated the compiler at work to be what I have at home and indeed I did not need to re-order the libs, But I did need uxtheme.

I'll have to look when I get home to see if there is something wrong with my compiler set up or if they did like a stealth update or something. ;)

**Comment by utelle** [comment]
I will add `uxtheme` to the list of libraries for the next release.

**Comment by utelle** [comment]
Commit a92258a275ad9b423475e41f24d060730ed9c3fb fixes this issue.
