### ISSUE TITLE
Link errors building unmodified wxSQLite3 over unmodified wxWidgets 3.1.1 (MSVS 17 Community)

### ISSUE THREAD

**Issue by ga2k** [utelle/wxsqlite3#44]
There are 28 unresolved external references in wxsqlite3.lib compiling an "As Downloaded" copy of wxSQLite3 4.1.0 with an "As Downloaded" copy of wxWidgets 3.1.1.

These unresolved externals rear their ugly heads in the static link versions of treeview and minimal. The DLL versions DO NOT HAVE this issue.

I have attached the MSVS output for one of the 8 failed builds.
[Output.txt](https://github.com/utelle/wxsqlite3/files/2407382/Output.txt)

**Comment by utelle** [comment]
Sorry, I can't confirm this issue. I tested static wxSQLite3 4.1.0 and wxWidgets 3.1.1 builds with VS2015 and VS2017 in 32-bit as well as 64-bit - all builds succeeded without errors.

I suspect that you have some sort of misconfiguration in your development environment. The build files for MSVS coming with wxSQLite3 use a property file `wx_setup.props` for adjustments to the actual development environment. Maybe you have to adjust the property file to match your environment (i.e. `wxRootDir` must point to the right directory). Or your static wxWidgets build was built with a different compiler version ...

**Comment by ga2k** [comment]
Thanks for your attention.

to reproduce, I had downloaded a fresh version of wxWidgets, ran the installer, did a "Batch Build" in the VS2017 IDE with all projects selected, and all wxWidgets projects built without errors. Then I set the Windows environment variable "WXWIN=D:\Libs\wxWidgets\wxWidgets-3.1.1", downloaded wxSQLite3  and did a "Batch Build" of wxsqlite3_vc15.sln with all projects selected. 

I'll try again. Knowing it worked for you is encouraging. I'll look into that props file, cause wxWidgets has its own, and see if there is anything amiss.

Thanks again.

**Comment by utelle** [comment]
Personally, I usually use the wxWidgets ZIP archives, not the installer, but that shouldn't make a difference. And if you really built **all** wxWidgets configurations, using "Batch build" for wxSQLite3 should work, too. However, I would recommend to just build those configurations you actually intend to use for your own development.

I used "Build solution" just to test the static builds, but again this shouldn't make a difference.

**Comment by utelle** [comment]
AFAICT there is no issue with the wxSQLite3 build system. Therefore I'm closing this issue.

Please feel free to reopen, if you have evidence that the wxSQLite3 build system is to blame for any build issues.
