### ISSUE TITLE
GetExpandedSQL has a memory leak

### ISSUE THREAD

**Issue by ga2k** [utelle/wxsqlite3#45]
Using `GetExpandedSQL()` on a `wxSQLite3Statement` causes a memory leak. Tracing into `GetExExpandedSQL()` takes us to a function in SQLite3, namely `sqlite3_expanded_sql()`. This function has the comment that **_The caller is responsible for freeing the returned string by passing it to sqlite3_free()_** on the returned pointer.

As `GetExpandedSQL()` converts the string returned to it into a `wxString`, `wxString` does it's own freeing of the memory, but it certainly doesn't know about, or call, `sqlite3_free().`

This causes a memory leak. If this is by design, the documentation for `GetExpandedSQL()` should advise the user of the fact. If not, then here is a proposed fix of the code. It (by nessessity) removes the const from the call to `sqlite3_expanded_sql(),` then calls sqlite3_free() on the pointer after the wxString creation.

```
wxString wxSQLite3Statement::GetExpandedSQL() const
{
   wxString sqlString = wxEmptyString;

#if SQLITE_VERSION_NUMBER >= 3014000

   CheckStmt();
   /*const*/ char* sqlLocal = sqlite3_expanded_sql(m_stmt->m_stmt);
   if (sqlLocal != NULL) sqlString = wxString::FromUTF8(sqlLocal);
   sqlite3_free(sqlLocal);  /* NEW CODE */

#endif
   return sqlString;
}

```
(also in wxString `wxSQLite3ResultSet::GetExpandedSQL()` const)

**Comment by utelle** [comment]
Thanks for reporting the issue. Not freeing the string returned by `sqlite3_expanded_sql` is simply an oversight. This will be fixed in the upcoming release due within the next few days.

**Comment by utelle** [comment]
Commit 9806ec3d93f1a9f8ba662a09911a1ff81e7ced49 fixes the issue.
