### ISSUE TITLE
Build errors in VS12(11) project 

### ISSUE THREAD

**Issue by Kvaz1r** [utelle/wxsqlite3#47]
When I tried to build the library with solution wxsqlite3_vc11.sln from build directory I got this errors: 

```
1>ClCompile:
1>  sqlite3secure.c
1>...\wxsqlite3-4.3.0\sqlite3secure\src\codecext.c(336): error C2143: синтаксическая ошибка: отсутствие ";" перед "тип"
1>...\wxsqlite3-4.3.0\sqlite3secure\src\codecext.c(337): error C2065: dbIndex: необъявленный идентификатор
1>..\sqlite3secure\src\sqlite3secure.c(191): error C2275: CodecParameter: недопустимое использование этого типа в качестве выражения
1>          ...\wxsqlite3-4.3.0\sqlite3secure\src\codec.c(1437): см. объявление "CodecParameter"
1>
```
The reason of the errors that VS12(11) hasn't support for C99 (or has very limited). So all declarations need to be before any blocks.

**Comment by utelle** [comment]
Thanks for reporting this issue.

For the release of version 4.3.0 I already fixed a few similar issues reported by another developer. Currently I develop wxSQLite3 using VS2015 (which does not produce these errors). I will consider to reinstall an older VS version for testing.

I will fix the code within the next days.

**Comment by utelle** [comment]
Commit 8449e4d7f4997c7dd007f98241f16ead79bc2e46 fixes the issue.
