### ISSUE TITLE
EOL problem with files in git repo

### ISSUE THREAD

**Issue by slodki** [utelle/wxsqlite3#48]
There are multiple text files in the repo stored with CRLF.

From `man gitattributes`:
> eol
This attribute sets a specific line-ending style to be used in the working directory. It enables end-of-line conversion without any content checks, effectively setting the text attribute. Note that setting this attribute on paths which are in the index with CRLF line endings may make the paths to be considered dirty. Adding the path to the index again will normalize the line endings in the index.
> [...]
> Note
When text=auto conversion is enabled in a cross-platform project using push and pull to a central repository the text files containing CRLFs should be normalized.

Please verify before each commit that text files are normalized (EOL=LF only).

See moneymanagerex/moneymanagerex#1890 for affected files.

**Comment by utelle** [comment]
I'm a bit puzzled, how this could and can happen. Shouldn't the file `.gitattributes` handle this automatically?

**Comment by slodki** [comment]
This can be related to folowing warning from `man gitattributes`:
> **eol**
> This attribute sets a specific line-ending style to be used in the working directory. It enables end-of-line conversion without any content checks, effectively setting the text attribute. Note that **setting this attribute on paths which are in the index with CRLF line endings may make the paths to be considered dirty**. Adding the path to the index again will normalize the line endings in the index.

**Comment by utelle** [comment]
As far as I understood it, the issue should affect only files having the "wrong" line ending that were added **before** `.gitattributes` was used to define the default eol behaviour. That is, it shouldn't occur anymore in the future.

Thanks for cleaning up the files.
