### ISSUE TITLE
./acregen.sh fails in build30

### ISSUE THREAD

**Issue by hasufell** [utelle/wxsqlite3#5]
```sh
# ./acregen.sh 
aclocal-1.15: error: configure.ac:21: file '../../../build/autoconf/wxcode.m4' does not exist
```

related to https://github.com/utelle/wxsqlite3/blob/master/build30/configure.ac#L21

which is a completely non-understandable directory that is outside of the project directory.

**Comment by utelle** [comment]
Sorry. I just forgot to update the path in `configure.ac` in directory `build30` (as I did for `configure.ac` in directory `build28`). I've adjusted the path and committed the file. Please try again. Thanks.

**Comment by utelle** [comment]
I assume the modified file `configure.ac` worked for you. So I'm going to close this issue.
