### ISSUE TITLE
warning: passing 'const char *' to parameter of type 'const unsigned char *' converts between pointers to integer types with different sign

### ISSUE THREAD

**Issue by arthurcn** [utelle/wxsqlite3#50]
sqlite3secure/src/codec.c:
Line 961:
const unsigned char* zRaw = (const unsigned char*) userPassword + 4;
Line:2290
const char* salt = (const char*) wxsqlite3_codec_data(db, nameParam2, "cipher_salt");

sqlite3secure/src/codecext.c
Line 236:
if ((cipherSalt != NULL) && (strlen((const char*)cipherSalt) >= 2 * KEYSALT_LENGTH) && IsHexKey(cipherSalt, 2 * KEYSALT_LENGTH))

**Comment by utelle** [comment]
Thanks for making PR #51 fixing these warning messages.
