### ISSUE TITLE
wxSQLite3Transaction::Commit() may fails silently

### ISSUE THREAD

**Issue by AliKet** [utelle/wxsqlite3#58]
Hi

My question is how to report unsuccessful commits if the `wxSQLite3Transaction::Commit()` keeps eating all thrown exceptions if something goes wrong when trying to commit the transaction (i.e: a **FK** violation) ?

I had to re-throw the exception from Commit() to finally know that may script was failing due to FK violation:

```
void wxSQLite3Transaction::Commit()
{
  try
  {
    m_database->Commit();
  }
  catch (...)
  {
    m_database->Rollback();
    throw; // rethrow
  }
  m_database = NULL;
}
```

I know i know, this not the correct solution and i just want to draw your attention to this problem.

Thank you.

**Comment by utelle** [comment]
Thank you for bringing this problem to my attention.

You are right. **Commit** should not fail silently. The application should have a chance to detect that the commit failed and to find out what went wrong.

Most likely rethrowing the exception is the best approach to solve the problem. However, I'll do some research whether other, maybe preferrable, approaches exist.

**Comment by utelle** [comment]
Commit eee2509a240cc3e79e6c16f0f1d9c51f55956f0e should fix the issue.

The explicit Commit and Rollback methods of wxSQLite3Transaction no longer catch exceptions. Instead exceptions will be propagated as usual. That is, if a Commit fails, an exception is thrown and the wxSQLite3Transaction destructor will try to perform a Rollback. However, the exception from the Commit has to be catched elsewhere in the application.

Please reopen this issue if necessary.
