### ISSUE TITLE
Removal of option to load SQLite library dynamically

### ISSUE THREAD

**Issue by utelle** [utelle/wxsqlite3#61]
Since wxSQLite3 version 3.5.0 (released in January 2017) the source code of the SQLite library is an integrated part of wxSQLite3 to simplify building the component and to make it easier to keep the features supported by SQLite and the wxSQLite3 wrapper in sync.

Using the symbol `wxUSE_DYNAMIC_SQLITE3_LOAD` it is currently still possible to select the option to load the SQLite library at runtime (DLL resp shared object). However, this opens the risk of loading a SQLite version that was not compiled with options matching those used for building the wxSQLite3 wrapper.

Therefore it is intended to remove the option to load SQLite at runtime from the next major release of wxSQLite3, unless a significant number of wxSQLite3 users object to this change.

Please share your opinions. Thanks.

**Comment by Deamhan** [comment]
Good idea. I didn't add this option to CMakeLists.txt in view of it.

**Comment by utelle** [comment]
The option to dynamically load the SQLite library will be removed in version **_5.x_** of **wxSQLite3**  (see also issue #72).
