### ISSUE TITLE
ReKey() function makes no use of cipher provided

### ISSUE THREAD

**Issue by MJaoune** [utelle/wxsqlite3#75]
The function ReKey() does not make use of the provided cipher whether it was provided or not, this causes the Open() function to fail to open a database if the cipher was used for a database that was encrypted using ReKey().

Here is the code snippet from wxsqlite.cpp:

```
void wxSQLite3Database::ReKey(const wxSQLite3Cipher& cipher, const wxMemoryBuffer& newKey)
{
#if WXSQLITE3_HAVE_CODEC
  CheckDatabase();
  int rc = sqlite3_rekey(m_db->m_db, newKey.GetData(), (int) newKey.GetDataLen());
  if (rc != SQLITE_OK)
  {
    const char* localError = sqlite3_errmsg(m_db->m_db);
    throw wxSQLite3Exception(rc, wxString::FromUTF8(localError));
  }
#else
  wxUnusedVar(newKey);
  throw wxSQLite3Exception(WXSQLITE_ERROR, wxERRMSG_NOCODEC);
#endif
}
```

The **cipher** parameter was not mentioned in the whole function.

**Comment by utelle** [comment]
Thanks for reporting this bug. A fix will be provided within the next few days.

**Comment by utelle** [comment]
Commit 73964eee420416eda0cff32de0e4eca4be4f529b should fix the issue. Please give it a try. Thanks.

**Comment by MJaoune** [comment]
Tested AES128, AES256 and ChaCha20, all working as expected. Thanks Ulrich! And thanks for the quick fix.

**Comment by utelle** [comment]
Thanks for the feedback ... now closing this issue.
