### ISSUE TITLE
Missing icuin64.dll

### ISSUE THREAD

**Issue by lazna** [utelle/wxsqlite3#79]
Windows 7 32bit, just downloaded last version of sqlite3shellicu.exe, installed into same directory as two bundled libraries. When trying to start sqlite3shellicu.exe, got GUI message 'icuin64.dll' missing. MSVCR 2015-2019 32bit installed.

What am I doing wrong?

**Comment by utelle** [comment]
The ICU DLLs are currently not included in the pre-compiled binaries - as is mentioned in the readme file included in the archive:

> The required ICU DLLs are not included in this archive; they have
to be downloaded from
>
> https://github.com/unicode-org/icu/releases/latest
>
> ICU support for SQLite3 is based on the pre-built ICU Libraries v64.2.
These are compiled for 32/64-bit Windows, using Visual Studio 2017.

That is, you have to download one of the following ICU packages, depending on whether you intend to use the 32-bit or 64-bit version: 

- [ICU 32-bit](https://github.com/unicode-org/icu/releases/download/release-64-2/icu4c-64_2-Win32-MSVC2017.zip)
- [ICU 64-bit](https://github.com/unicode-org/icu/releases/download/release-64-2/icu4c-64_2-Win64-MSVC2017.zip)

I will consider to provide self-contained archives in the future.

**Comment by lazna** [comment]
Thanks a lot, I am not reading carefully. It working now.
