### ISSUE TITLE
Program minimal in wxsqlite3-4.5.0

### ISSUE THREAD

**Issue by Carluccio** [utelle/wxsqlite3#82]
With mingw64 / 8.1 the minimal program, static release and debug 64, ends with an error due to the wrong sequence of the system libraries.
The right sequence in wxwidgets.lua should be the following:
links {"kernel32", "user32", "gdi32", "comdlg32", "winspool", "winmm", "shell32", "shlwapi", "comctl32",
"ole32", "oleaut32", "uuid", "rpcrt4", "advapi32", "version", "wsock32", "wininet", "oleacc", "uxtheme"}

**Comment by utelle** [comment]
Since I seldom use static builds of wxWidgets I have to admit that I didn't explicitly test this configuration.

I will adjust the lua file, and the affected build files.

**Comment by utelle** [comment]
Commit 022fa3011a9896a99258d1080587a790d2379b21 should fix the issue.

**Comment by Carluccio** [comment]
Yes, make sure this solves the problem well. I see that you will also be present for your most welcome future versions.
Regards
Carlo

**Comment by utelle** [comment]
Currently my capacities are a bit limited, but I do my best to provide updates, whenever new versions of SQLite are released. It is planned to modernize and enhance the provided API, but there is not yet a schedule for those activities.
