### ISSUE TITLE
Supporting database encryption for SQLite version 3.32.0 and later

### ISSUE THREAD

**Issue by utelle** [utelle/wxsqlite3#85]
Critical changes to the public SQLite code were introduced on Feb 7, 2020: [“Simplify the code by removing the unsupported and undocumented SQLITE_HAS_CODEC compile-time option”](https://www.sqlite.org/src/timeline?c=5a877221ce90e752). With the release of SQLite version 3.32.0 on May 22, 2020 these changes finally took officially effect, although they weren't officially announced.

As a consequence, updating the _wxSQLite3 encryption extension_ to support SQLite version 3.32.0 and later is currently impossible.

Work is in progress in a separate project, [SQLite3 Multiple Ciphers](https://github.com/utelle/SQLite3MultipleCiphers), to provide a new implementation of the encryption extension capable of supporting SQLite version 3.32.0 and later. However, the new implementation is not yet production ready.

Currently I see the following options, how to proceed with introducing the new implementation of the encryption extension to **wxSQLite3**:

1. Introduce it _immediately_, even if it is not yet finalized.
2. Do not introduce it until it is finalized and officially released.
3. Introduce it only after wxSQLite3 has been _modernized_ (using C++11/14/17 features).

Feedback, how to proceed with the transition to the new implementation, would be very welcome.

**Comment by jaskinn** [comment]
I think option 2.

**Comment by Kvaz1r** [comment]
I also think that option 2 is better.

**Comment by utelle** [comment]
@jaskinn @Kvaz1r : Thanks for the feedback.

Taking option 2 will delay an update of **wxSQLite3** for some time - maybe a couple of weeks, maybe longer. I want to let [SQLite3 Multiple Ciphers](https://github.com/utelle/SQLite3MultipleCiphers) mature for a certain period of time, because (usually minor) bugs are still popping up from time to time, although the new implementation already is rather stable.

**Comment by utelle** [comment]
A first release of [SQLite3 Multiple Ciphers](https://github.com/utelle/SQLite3MultipleCiphers) took place on [August 15, 2020](https://github.com/utelle/SQLite3MultipleCiphers/releases/tag/v1.0.0).

So the prior wxSQLite3 encryption extension could be replaced by the new implementation, and the release [wxSQLite3 4.6.0](https://github.com/utelle/wxsqlite3/releases/tag/v4.6.0) could be made.
