### ISSUE TITLE
x64 MinGW build cannot find setup.h (4.5.1)

### ISSUE THREAD

**Issue by nzod** [utelle/wxsqlite3#86]
Using the MinGW version that ships with CodeBlocks 20.03:
(x86_64-posix-seh-rev0 8.1.0)
```
mingw32-make wxRootDir="[...]" wxShortVersionString="31" config=release_x64 wxsqlite3

[...]/include/wx/platform.h:154:10: fatal error: wx/setup.h: No such file or directory
```
The default release_x32 config builds fine. wxWidgets 3.1.3 was built (as 64-bit) beforehand with the same toolset, and works.

It's possible I'm overlooking something and in that case excuse my opening this as an issue.

**Comment by utelle** [comment]
AFAICT it is a question of a correctly set search path for include files. One of the search path used in the wxSQLite3 build files is

`$(wxRootDir)/lib/$(wxCompilerPrefix)$(wxArchSuffix)_lib/msw$(wxSuffix)`

In that location reside the build specific header files of wxWidgets. For the configuration `release_x64` this results in

`$(wxRootDir)/lib/gcc_x64_lib/mswu`

Please check whether your 64-bit wxWidgets library was built in that location and whether the header file `wx/setup.h` exists at that location. 

Most likely the library path for your wxWidgets build is different. In that case you will have to adjust the wxSQLite3 build files. In most cases it is sufficient to adjust the settings in the config file `config.gcc`.

**Comment by nzod** [comment]
Oh, the `_x64` was indeed missing from the directory name.

Thank you for your time and suggestions, and again apologies for using the tracker for support basically.

**Comment by utelle** [comment]
Glad to hear that you could sort out the problem.

Feel free to use the issue tracker for any kind of questions regarding wxSQLite3.
