### ISSUE TITLE
wxSQLite3Transaction

### ISSUE THREAD

**Issue by AliKet** [utelle/wxsqlite3#88]
Hi,

`wxSQLite3`, for good reasons, disallow creating instances of `wxSQLite3Transaction` dynamically. but as we have now `std::unique_ptr, wxScopedPtr` and the like, i wonder if the authors of this great lib be kind and alleviate the requirement a little by adding some preprocessor (e.g. `wxSQLITE3_ALLOW_DYNAMIC_CREATION`) and if defined by user code something like this would be possible:
`std::unique_ptr<wxSQLite3Transaction> trans(db);`
would be possible and with the same guarantee as before.

P.S. in my application i have a function `MyFuntionc` which should create its own transaction only if it is called alone, i.e. not as part of a complex operation which a transaction is already active. and AFAIK sqlite3 doesn't support  nested transactions yet?

TIA!

**Comment by AliKet** [comment]
Just ignore my post! cause i think i found a better solution to my problem.

Thank you.

**Comment by utelle** [comment]
> `wxSQLite3`, for good reasons, disallow creating instances of `wxSQLite3Transaction` dynamically. but as we have now `std::unique_ptr, wxScopedPtr` and the like, i wonder if the authors of this great lib be kind and alleviate the requirement a little by adding some preprocessor (e.g. `wxSQLITE3_ALLOW_DYNAMIC_CREATION`) and if defined by user code something like this would be possible:
> `std::unique_ptr<wxSQLite3Transaction> trans(db);`
> would be possible and with the same guarantee as before.

It is planned to modernize **wxSQLite3** using features from C++11 or later. In this course I will look into this issue.

> P.S. in my application i have a function `MyFuntionc` which should create its own transaction only if it is called alone, i.e. not as part of a complex operation which a transaction is already active. and AFAIK sqlite3 doesn't support nested transactions yet?

Transactions created using `BEGIN` ... `COMMIT` do not nest. However, SQLite3 supports nested transactions via the [savepoint concept](https://www.sqlite.org/lang_savepoint.html).

`wxSQLite3Transaction` is currently limited to not nested transactions.
