### ISSUE TITLE
Errors while build (MSVC10, Release, x64)

### ISSUE THREAD

**Issue by AndreasMartin72** [utelle/wxsqlite3#9]
Hello Mr. Telle,

the _UNICODE macro seems not to modify the wxw library file name:
`1>LINK : fatal error LNK1181: cannot open input file 'wxbase31.lib'`
As a workaround I renamed the wxShortVersionString from the property page from "31" to "31u".
Now a source seems to be missing:
`1>LINK : fatal error LNK1181: cannot open input file 'wxregex.lib'`

Kindly regards,
Andreas Martin

**Comment by utelle** [comment]
Thanks for reporting the issue.

The property `CharacterSet` that decides which library suffix is used, is always set correctly. However, the problem seems to be the property `Configuration`. I overlooked that `premake5` added a postfix `Win64` to the configuration names for 64 bit builds. This is not taken into account by the condition expressions in the property file `wx_setup.props`.

I have to check whether I can persuade `premake5` to not use the postfix `Win64` in configuration names or whether I will have to adjust the condition expressions.

**Comment by utelle** [comment]
Changing the platform names from `Win32` resp. `Win64` to `x32` resp. `x64` in the `premake5` script solved the problem.

Please reopen the issue if necessary.

**Comment by AndreasMartin72** [comment]
Now two points remain:
1st:
```
1>  sqlite3secure.c
1>d:\git\wxsqlite3\sqlite3\secure\src\codec.h(49): fatal error C1017: Ungültiger Ausdruck für Ganzzahlkonstante
```
Looking at line 49, seeing `CODEC_TYPE` is defined empty: `#if == 2`
In the preprocessor definition CODEC_TYPE=$(CODEC_TYPE), least seems not to be defined.
Probably the missing "wx_setup" properties takes into account...

2nd:
The property page "wx_setup" is missing now. Somehow $(wxRootDir) (and more) seems to be defined there. I got it working when setting the path manually...

**Comment by utelle** [comment]
Sorry, I was not able to reproduce the problem when I compiled wxSQLite3 with MSVC 2010 a few minutes ago.

The property file `wx_setup.props` is referenced in `wxsqlite3_vc10_wxsqlite3.vcxproj` as it should. And the repository holds a version of `wx_setup.props` that you have to adjust to your configuration either by editing it directly or by overwriting it using a property file `wx_local.props`.

Make sure that `wx_setup.props` is accessible and reflects your configuration (for example the value of `wxRootDir` for which the default is the environment variable `WXWIN`).

If you display from within Visual Studio the properties of the `wxsqlite3` project, and go for example to the category `C / C++ - Preprocessor` and click on `Edit` for the `Preprocessor Definitions` you have a button labelled `Macros` in the dialog which allows you to see the list of defined macros. If you don't see there quite a number of macros which names start with `wx`, then something is wrong with your property files.

However, if Visual Studio couldn't find the file `wx_setup.props` at all, you would get an error message telling you that the projetc can't be loaded. So maybe you did overwrite `wx_setup.props` with an invalid or incomplete `wx_local.props` file.

**Comment by AndreasMartin72** [comment]
Interesting:
On MSVC 2010 professional (english Version), Win7, there is that property page, but on MSVC 2010 (german version) ultimate it's not... :-(

**Comment by utelle** [comment]
Unfortunately I don't have access the ultimate edition of Visual Studio. I have MSVC 2010 and 2015 Professional (English) installed. In both compiling wxSQLite3 works flawlessly with the provided project files.

Of which property page are you talking? You don't see the macro expansions list? That would be hardly believable.

On the property pages you usually see a treeview on the left. Look under `Configuration Properties / C/C++ / Preprocessor`. There should be a line `Preprocessor Definitions` on the right. Clicking `Edit` in the value area should show the mentioned dialog with the `Macros` button.

Additionally, it could maybe help to see the final command line (look under `Configuration Properties / C/C++ / Command Line`).

Finally, I would like to know whether you compiled the wxWidgets library yourself. Did you use the solution file in directory `build/msw`? For MSVC 2010+ it uses also property files (`wx_config.props` and `wx_setup.props`). If that worked for you, I don't see why it shouldn't work for `wxSQLite3`.

**Comment by AndreasMartin72** [comment]
I send you 2 screenshots to make it believable ;-)
![2017-01-30 12_50_50-wxsqlite3_vc10 - microsoft visual studio](https://cloud.githubusercontent.com/assets/11562654/22422139/262b1c78-e6eb-11e6-98e8-a56a14f70669.jpg)
![2017-01-30 12_51_50-release-eigenschaftenseiten](https://cloud.githubusercontent.com/assets/11562654/22422140/2664231a-e6eb-11e6-9b71-f233153548e1.jpg)

**Comment by utelle** [comment]
Ok, I see that `wx_setup.props` isn't shown below the configurations. However, I have no idea, why. In my installation it is shown. What happens, if you try to add it manually by right-clicking on the configuration name and selecting `Add Existing Property Sheet`?

I added 2 arrows to your screenshot of the property sheet, where you should look for further information:
![msvc-properties-arrows](https://cloud.githubusercontent.com/assets/11139874/22423735/4cef24dc-e6f3-11e6-954c-bc1ae5179f7b.jpg)

The first place is for the preprocessor. You should be able to see something like the following:
![msvc-2010-macros](https://cloud.githubusercontent.com/assets/11139874/22424038/ea84a43c-e6f4-11e6-9a07-15f21fc1efbc.jpg)

And the final command line should look like this (see expanded CODEC_TYPE macro):
![msvc-2010-cmdline](https://cloud.githubusercontent.com/assets/11139874/22423878/1fa65f3a-e6f4-11e6-9ac7-89562f540112.jpg)

If the `wx` macros are not in the macro expansion list, then there is definitely a problem with your Visual Studio.

Did you just update your wxSQLite3 folder by downloading the latest github repository without removing remains from prior builds? If yes: Do you experience the same problem if you start from scratch in a clean directory? That is, no remains from prior builds of wxSQLite3?

**Comment by AndreasMartin72** [comment]
Her are my results:

![2017-01-30 14_49_20-release-eigenschaftenseiten](https://cloud.githubusercontent.com/assets/11562654/22425437/59e9284c-e6fb-11e6-997c-2b1d6671d590.jpg)
![2017-01-30 14_46_10-praprozessordefinitionen](https://cloud.githubusercontent.com/assets/11562654/22425438/59ea666c-e6fb-11e6-839f-f36b95083942.jpg)

Sure I first did a revert then a clean and then pulled the recent master.
I see, that premake5 doesn't generate the solution (.sln). I try to start from scratch, as you supposed...

**Comment by AndreasMartin72** [comment]
I got it:
your versions on github are ok!

As you suggested:
```
Changing the platform names from Win32 resp. Win64 to x32 resp. x64 in the premake5 script solved the problem.

Please reopen the issue if necessary.
```
I ran premake to generate the project files `premake5 vs2010` (WXWIN is defined on my machine).

I fear there must be more options set to build correct project files. After that step I stuck in trouble.

**Comment by utelle** [comment]
Please use the pre-generated solution files in directory `build`. Those files were generated with a modified version of `premake5` that adds the magic for including the property file `wx_setup.props` from the project files (`*.vcxproj`).

If you used project files you generated yourself, it will not work, unfortunately.

P.S.: I asked the premake team to add a way for generating property files references in July 2016. However, nothing has happened since then. Therefore I modified `premake5` myself to overcome this deficiency.

**Comment by AndreasMartin72** [comment]
Ah, ok. I took the actual (alpha) version of premake5 and didn't expected any extra salt :-)
:+1: for your support and experience!

**Comment by utelle** [comment]
Of course, I would prefer to use an unmodified version of premake. However, for the users of my components it's more convenient to be able to adjust build options easily by editing a single property file, instead of having to regenerate the project files.

Thanks for testing the new build files and reporting your issues! This helps to make `wxSQLite3` better. (and I will transfer what I have learned to my other component `wxPdfDocument` as it suffers from the same issue for `x64` builds.)
