### ISSUE TITLE
wx/setup.h: No such file or directory

### ISSUE THREAD

**Issue by austin2209** [utelle/wxsqlite3#92]
Hi,
I'm new to all the wxWidgets thing. I successfully complied and used wxWidgets-3.0.5 in CodeBlocks, but i couldn't do the same for wxsqlite3.

wxWidgets was compiled with this options:
`mingw32-make -f makefile.gcc BUILD=release SHARED=1 UNICODE=1 MONOLITHIC=0`

But when i try to compile wxWidgets with matching options in config.gcc using this:
`mingw32-make makefile config=release_dll_win64 all`

I gets this error:
```
"==== Building wxsqlite3 (release_dll_win64) ===="
wxsqlite3.cpp
In file included from C:\wxWidgets-3.0.5/include/wx/defs.h:27,
                 from C:\wxWidgets-3.0.5/include/wx/wxprec.h:12,
                 from ../src/wxsqlite3.cpp:17:
C:\wxWidgets-3.0.5/include/wx/platform.h:183:10: fatal error: wx/setup.h: No such file or directory
 #include "wx/setup.h"
          ^~~~~~~~~~~~
compilation terminated.
mingw32-make[1]: *** [wxsqlite3.make:256: obj/gcc/Win64/Release_DLL/wxsqlite3/wxsqlite3.o] Error 1
mingw32-make: *** [makefile:86: wxsqlite3] Error 2
```
"setup.h" exist in "include\wx\msw" not in "include\wx"

I would be grateful for any help, Thank you!

**Comment by austin2209** [comment]
Hi again,
I copied "setup.h" to "include\wx", and now i'm getting this error:
```
"==== Building wxsqlite3 (release_dll_win64) ===="
Linking wxsqlite3
C:/Program Files/CodeBlocks/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxmsw30u_core
C:/Program Files/CodeBlocks/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxbase30u
C:/Program Files/CodeBlocks/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxjpeg
C:/Program Files/CodeBlocks/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxpng
C:/Program Files/CodeBlocks/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxzlib
C:/Program Files/CodeBlocks/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxtiff
C:/Program Files/CodeBlocks/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxexpat
C:/Program Files/CodeBlocks/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxregexu
collect2.exe: error: ld returned 1 exit status
mingw32-make[1]: *** [wxsqlite3.make:197: ../lib/gcc_x64_dll/libwxsqlite3_msw30u.a] Error 1
mingw32-make: *** [makefile:86: wxsqlite3] Error 2
```

It seems the options in config.gcc file are ignored, wxCompilerPrefix, wxCfg and wxVendor have no effect

**Comment by austin2209** [comment]
I replaced "wx/setup.h" with "wx/msw/setup.h" in "platform.h:183" and the "wx/setup.h: No such file or directory" error is gone.
I renamed "wxWidgets-3.0.5\lib\gcc_xdll" to "wxWidgets-3.0.5\lib\gcc_x64_dll" and removed the wxCompilerPrefix, wxVendor from wxWidgets DLLs and the "wxsqlite3.make:197: ../lib/gcc_x64_dll/libwxsqlite3_msw30u.a] Error 1" error is gone.

But now if i run:
`mingw32-make makefile config=release_dll_win64 wxsqlite3`

I get:
```
mingw32-make: Nothing to be done for 'makefile'.
"==== Building wxsqlite3 (release_dll_win64) ===="
Creating obj/gcc/Win64/Release_DLL/wxsqlite3
wxsqlite3_version.rc
sqlite3mc_amalgamation.c
wxsqlite3.cpp
Linking wxsqlite3
```
But no DLLs are created, i tried:
`mingw32-make makefile config=release_dll_win64 minimal`

And i get this:
```
"==== Building wxsqlite3 (release_dll_win64) ===="
"==== Building minimal (release_dll_win64) ===="
Creating obj/gcc/Win64/Release_DLL/minimal
Creating bin/gcc/Win64/Release_DLL
minimal.rc
minimal.cpp
Linking minimal
obj/gcc/Win64/Release_DLL/minimal/minimal.o:minimal.cpp:(.text+0x3cd): undefined reference to `wxSQLite3Database::wxSQLite3Database()'
obj/gcc/Win64/Release_DLL/minimal/minimal.o:minimal.cpp:(.text+0x556): undefined reference to `wxSQLite3Database::Open(wxString const&, wxSQLite3Cipher const&, wxString const&, int)'
obj/gcc/Win64/Release_DLL/minimal/minimal.o:minimal.cpp:(.text+0x5c3): undefined reference to `wxSQLite3Database::GetKeySalt(wxString const&) const'
obj/gcc/Win64/Release_DLL/minimal/minimal.o:minimal.cpp:(.text+0x718): undefined reference to `wxSQLite3Database::ExecuteScalar(char const*)'
obj/gcc/Win64/Release_DLL/minimal/minimal.o:minimal.cpp:(.text+0x7eb): undefined reference to `wxSQLite3Database::ExecuteQuery(char const*)'
obj/gcc/Win64/Release_DLL/minimal/minimal.o:minimal.cpp:(.text+0x7fb): undefined reference to `wxSQLite3ResultSet::NextRow()'
...............
```

**Comment by utelle** [comment]
> I'm new to all the wxWidgets thing. I successfully complied and used wxWidgets-3.0.5 in CodeBlocks, but i couldn't do the same for wxsqlite3.
> 
> wxWidgets was compiled with this options:
> `mingw32-make -f makefile.gcc BUILD=release SHARED=1 UNICODE=1 MONOLITHIC=0`

Maybe this command builds wxWidgets in 32-bit mode. You have to make sure that you build the wxWidgets version you really want to use. Maybe you should consider to use pre-built wxWidgets libraries/DLLs ...

> But when i try to compile wxWidgets with matching options in config.gcc using this:
> `mingw32-make makefile config=release_dll_win64 all`

However, obviously you selected a 64-bit build for wxSQLite3 ...

> I gets this error:
> 
> ```
> "==== Building wxsqlite3 (release_dll_win64) ===="
> wxsqlite3.cpp
> In file included from C:\wxWidgets-3.0.5/include/wx/defs.h:27,
>                  from C:\wxWidgets-3.0.5/include/wx/wxprec.h:12,
>                  from ../src/wxsqlite3.cpp:17:
> C:\wxWidgets-3.0.5/include/wx/platform.h:183:10: fatal error: wx/setup.h: No such file or directory
>  #include "wx/setup.h"
>           ^~~~~~~~~~~~
> compilation terminated.
> mingw32-make[1]: *** [wxsqlite3.make:256: obj/gcc/Win64/Release_DLL/wxsqlite3/wxsqlite3.o] Error 1
> mingw32-make: *** [makefile:86: wxsqlite3] Error 2
> ```

... and this error message indicates that the 64-bit wxWidgets build is **not** available - at least not at the location you configured via `config.gcc`.

> "setup.h" exist in "include\wx\msw" not in "include\wx"

Well, the wxWidgets build copies a version of `setup.h` to the library directory. That is, the file `setup.h` is searched for in the following location:

`WXROOT/lib/gcc_x64_dll/mswu/wx/setup.h`

where `WXROOT` designates the root directory of your wxWidgets installation. The part `gcc_x64_dll` may look slightly different, depending on the options chosen on building wxWidgets.

The makefile of wxSQLite3 adds the equivalent of `WXROOT/lib/gcc_x64_dll/mswu` to the compiler search path. That is, if the wxWidgets build corresponding to the selected build configuration of wxSQLite3 exists, then the file `setup.h` will be found.

> I copied "setup.h" to "include\wx",

This is a really bad idea. You should not tamper with the source directories of wxWidgets. This will make things only worse ... as you experienced. In general you should be able to configure the location where the compiler looks for the wxWidgets build via `config.gcc` in the wxSQLite3 build directory.

**Comment by austin2209** [comment]
I tried different builds of wxWidgets including the pre-built wxWidgets DLLs, i also tried to build wxSQLite3 with `release_dll_win32` option and the other options, but i'm still getting `setup.h` not found.
I have wxWidgets in path, as you can see form the error, it did find wxWidgets root folder.
Thank you very much for your replay.

**Comment by austin2209** [comment]
With a fresh wxWidgets3.0.5 i added `COMPILER_VERSION=_x64` to wxWidgets's building command (like you mentioned [here](https://forums.wxwidgets.org/viewtopic.php?f=30&t=46788&hilit=x64+MinGW))  and rebuild it. But when i tried to build wxsqlite3-4.6.4 using:
`mingw32-make makefile config=release_dll_win64 all` i get this error and still no DLLs are created
```
mingw32-make: Nothing to be done for 'makefile'.
"==== Building wxsqlite3 (release_dll_win64) ===="
Creating obj/gcc/Win64/Release_DLL/wxsqlite3
Creating ../lib/gcc_x64_dll
wxsqlite3_version.rc
sqlite3mc_amalgamation.c
wxsqlite3.cpp
Linking wxsqlite3
"==== Building minimal (release_dll_win64) ===="
"==== Building treeview (release_dll_win64) ===="
Creating obj/gcc/Win64/Release_DLL/treeview
Creating obj/gcc/Win64/Release_DLL/minimal
Creating bin/gcc/Win64/Release_DLL
Creating bin/gcc/Win64/Release_DLL
A subdirectory or file bin\\gcc\\Win64\\Release_DLL already exists.
mingw32-make[1]: *** [minimal.make:211: bin/gcc/Win64/Release_DLL] Error 1
mingw32-make[1]: *** Waiting for unfinished jobs....
treeview.rc
minimal.rc
foldertree.cpp
projectlist.cpp
treeviewapp.cpp
treeviewsample.cpp
mingw32-make: *** [Makefile:96: minimal] Error 2
mingw32-make: *** Waiting for unfinished jobs....
Linking treeview
obj/gcc/Win64/Release_DLL/treeview/foldertree.o:foldertree.cpp:(.text+0x28c5): undefined reference to `wxSQLite3Database::ExecuteQuery(wxString const&)'
obj/gcc/Win64/Release_DLL/treeview/foldertree.o:foldertree.cpp:(.text+0x29a5): undefined reference to `wxSQLite3ResultSet::NextRow()'
obj/gcc/Win64/Release_DLL/treeview/foldertree.o:foldertree.cpp:(.text+0x29ba): undefined reference to `wxSQLite3ResultSet::GetInt(int, int) const'
obj/gcc/Win64/Release_DLL/treeview/foldertree.o:foldertree.cpp:(.text+0x29ce): undefined reference to `wxSQLite3ResultSet::GetInt(int, int) const'
obj/gcc/Win64/Release_DLL/treeview/foldertree.o:foldertree.cpp:(.text+0x29e1): undefined reference to `wxSQLite3ResultSet::GetInt(int, int) const'
...................
obj/gcc/Win64/Release_DLL/treeview/treeviewsample.o:treeviewsample.cpp:(.text+0x5a43): undefined reference to `wxSQLite3Statement::~wxSQLite3Statement()'
obj/gcc/Win64/Release_DLL/treeview/treeviewsample.o:treeviewsample.cpp:(.text+0x5a51): undefined reference to `wxSQLite3Statement::~wxSQLite3Statement()'
obj/gcc/Win64/Release_DLL/treeview/treeviewsample.o:treeviewsample.cpp:(.text+0x5aa6): undefined reference to `wxSQLite3Database::Rollback(wxString const&)'
collect2.exe: error: ld returned 1 exit status
mingw32-make[1]: *** [treeview.make:212: bin/gcc/Win64/Release_DLL/treeview.exe] Error 1
mingw32-make: *** [Makefile:106: treeview] Error 2
```
The compiler i'm using is x86_64-w64-mingw32 (Make 4.2.1 / gww 8.1.0 ) that comes with CodeBlocks 20.03

**Comment by utelle** [comment]
> I tried different builds of wxWidgets including the pre-built wxWidgets DLLs, i also tried to build wxSQLite3 with `release_dll_win32` option and the other options, but i'm still getting `setup.h` not found.

Well, this is not a wxSQLite3 issue, but a configuration issue with your wxWidgets installation. The error messages in your first post clearly indicate that either the path to wxWidgets was not set properly or the requested wxWidgets build is not available.

Configuration file `config.gcc` allows to set `wxRootDir ?= $(WXWIN)` That is, it is expected that environment variable WXWIN points to the root directory of wxWidgets. It seems you managed to configure this, otherwise you would have got many more error messages from the compiler.

Now, the question is, which builds of wxWidgets do you really have built successfully. Please inspect the `lib` directory of your wxWidgets installation. You should find directories there with names like `gcc_x64_dll` or `gcc810_x64_dll`. And below these directories there have to be additional directories `mswu` (Release) and `mswud` (Debug). If you use pre-compiled libraries, you have to use the development builds (having `Dev` in their file name) (not the release builds, because they don't have the `mswu` / `mswud` subdirectories).

The next step is to check whether the C++ header file search path is set up correctly. Invoke make in verbose mode and check the command line for the `-I` options. If the paths in these options are not correct, you have to adjust the settings in `config.gcc` accordingly.

> I have wxWidgets in path, as you can see form the error, it did find wxWidgets root folder.

That is good, but not enough. The relevant subdirectories in the `lib` directory have to exist, too.

Additionally, I would strongly recommend to clean up the wxSQLite3 build directory - for example, by removing the `obj` subdirectory, so that a complete new build is done. From the messages presented I get the impression that the wxSQLite3 library itself is not properly built and therefore the link step for the dependent samples fails.

The wxSQLite3 library/DLL should be found in `lib/gcc_x64_dll`, if the sources could be compiled and linked successfully.

Good luck!

**Comment by austin2209** [comment]
I downloaded wxWidgets's Dev pre-compiled libraries x64 (`gcc810_x64_dll`) and run `mingw32-make makefile config=release_dll_win64 wxsqlite3` wxsqlite3-4.6.4 seems to build but no DLLs are created just `libwxsqlite3_msw30u.a` in `lib/gcc_x64_dll`. 
This is the log with the `--debug` option:

```
GNU Make 4.2.1
Built for x86_64-w64-mingw32
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Updating makefiles....
Updating goal targets....
mingw32-make: Nothing to be done for 'makefile'.
 File 'wxsqlite3' does not exist.
Must remake target 'wxsqlite3'.
"==== Building wxsqlite3 (release_dll_win64) ===="
GNU Make 4.2.1
Built for x86_64-w64-mingw32
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Updating makefiles....
Updating goal targets....
 File 'all' does not exist.
   File '../lib/gcc_x64_dll/libwxsqlite3_msw30u.a' does not exist.
     File 'obj/gcc/Win64/Release_DLL/wxsqlite3/wxsqlite3_version.res' does not exist.
       File 'prebuild' does not exist.
         File 'obj/gcc/Win64/Release_DLL/wxsqlite3' does not exist.
        Must remake target 'obj/gcc/Win64/Release_DLL/wxsqlite3'.
     File 'obj/gcc/Win64/Release_DLL/wxsqlite3/sqlite3mc_amalgamation.o' does not exist.
     File 'obj/gcc/Win64/Release_DLL/wxsqlite3/wxsqlite3.o' does not exist.
     File '../lib/gcc_x64_dll' does not exist.
    Must remake target '../lib/gcc_x64_dll'.
Creating obj/gcc/Win64/Release_DLL/wxsqlite3
Creating ../lib/gcc_x64_dll
 File 'all' does not exist.
   File '../lib/gcc_x64_dll/libwxsqlite3_msw30u.a' does not exist.
     File 'obj/gcc/Win64/Release_DLL/wxsqlite3/wxsqlite3_version.res' does not exist.
       File 'prebuild' does not exist.
      Must remake target 'prebuild'.
      Successfully remade target file 'prebuild'.
    Must remake target 'obj/gcc/Win64/Release_DLL/wxsqlite3/wxsqlite3_version.res'.
     File 'obj/gcc/Win64/Release_DLL/wxsqlite3/sqlite3mc_amalgamation.o' does not exist.
    Must remake target 'obj/gcc/Win64/Release_DLL/wxsqlite3/sqlite3mc_amalgamation.o'.
wxsqlite3_version.rc
     File 'obj/gcc/Win64/Release_DLL/wxsqlite3/wxsqlite3.o' does not exist.
    Must remake target 'obj/gcc/Win64/Release_DLL/wxsqlite3/wxsqlite3.o'.
sqlite3mc_amalgamation.c
wxsqlite3.cpp
 File 'all' does not exist.
   File '../lib/gcc_x64_dll/libwxsqlite3_msw30u.a' does not exist.
 File 'all' does not exist.
   File '../lib/gcc_x64_dll/libwxsqlite3_msw30u.a' does not exist.
 File 'all' does not exist.
   File '../lib/gcc_x64_dll/libwxsqlite3_msw30u.a' does not exist.
  Must remake target '../lib/gcc_x64_dll/libwxsqlite3_msw30u.a'.
Linking wxsqlite3
 File 'all' does not exist.
Must remake target 'all'.
```

Then i changed nothing except building wxsqlite3-4.5.1 instead, and the wxSQLite3'd DLL was created.. Still getting `undefined reference to` error with the minimal/treeview target.

Thank you very much for your help/patience, i really appreciate it

**Comment by utelle** [comment]
> I downloaded wxWidgets's Dev pre-compiled libraries x64 (`gcc810_x64_dll`) and run `mingw32-make makefile config=release_dll_win64 wxsqlite3` wxsqlite3-4.6.4 seems to build but no DLLs are created just `libwxsqlite3_msw30u.a` in `lib/gcc_x64_dll`.

Well, the good thing is, you solved your primary problem with `wx/setup.h`. The bad thing is, you now discovered a problem with the MinGW/GCC build files (not related to `wx/setup.h`).

I have to admit that I only rarely use MinGW myself. So I didn't realize that the MinGW/GCC build files seem to be broken - at least for some configurations. I tested the DLL build myself this morning and have to confirm that you are right: there is no DLL. However, there is something fishy going on, because the `.a` file which gets build is in fact a DLL (but the link library is missing).

> Then i changed nothing except building wxsqlite3-4.5.1 instead, and the wxSQLite3'd DLL was created.

I'll have to check, which release introduced the broken MinGW/GCC build files. Of course, I will try to fix the issue for the next release (which will most likely happen in March or April shortly after the release of the next SQLite3 version).

> Still getting `undefined reference to` error with the minimal/treeview target.

Are you saying that you experience build problems with wxSQLite3 version 4.5.1 as well? Strange. If the build files were broken for more than a year, I had expected, that other developers would have reported that earlier.

**Comment by utelle** [comment]
I applied a minor adjustment to the MinGW/GCC build files. Thereafter doing a DLL build with MinGW/GCC worked for me. Please give it a try.

**Comment by utelle** [comment]
> Yes! your adjustment worked! The DLL is created. Thank you so much!!

Good to hear.

> Unfortunately the minimal/treeview samples still gives the `Undefined reference to` when building with `config=release_dll_win64`, **but** with `config=release_wxdll_win64` the samples compile/work perfectly without errors.

Sorry, I have no explanation for this. I tested it in my own environment and did not get any errors. Most likely there are still some remains around somewhere from your previous failed experiments.

Nevertheless, I'm going to close the issue. Reopen it, if you can provide evidence that the wxSQLite3 build files for MinGW/GCC do not work for a clean build.
